# spark-master.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: finstream
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      securityContext:
        runAsUser: 0  # Run as root
      containers:
      - name: spark-master
        image: bitnami/spark:3.4.0
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: PYTHONPATH
          value: "/project:/project/config"
        - name: HOME
          value: "/tmp"
        ports:
        - containerPort: 7077
          name: spark
        - containerPort: 8080
          name: webui
        volumeMounts:
        - name: project
          mountPath: /project
        - name: spark-libs
          mountPath: /opt/bitnami/python/lib/python3.11/site-packages
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        command:
        - sh
        - -c
        - |
          /opt/bitnami/python/bin/pip3 install --no-cache-dir python-dotenv PyYAML cassandra-driver confluent_kafka &&
          /opt/bitnami/spark/sbin/start-master.sh &&
          tail -f /opt/bitnami/spark/logs/spark--org.apache.spark.deploy.master.Master-1-*.out
      volumes:
      - name: project
        configMap:
          name: project-files
          items:
          - key: producer.py
            path: producer.py
          - key: consumer.py
            path: consumer.py
          - key: .env
            path: .env
          - key: __init__.py
            path: config/__init__.py
          - key: config.py
            path: config/config.py
          - key: config.yml
            path: config/config.yml
      - name: spark-libs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: finstream
spec:
  selector:
    app: spark-master
  ports:
  - name: spark
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: webui
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP