apiVersion: v1
kind: Namespace
metadata:
  name: finstream
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-pvc
  namespace: finstream
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: finstream
data:
  cassandra.yaml: |
    data_file_directories:
      - /var/lib/cassandra/data
    commitlog_directory: /var/lib/cassandra/commitlog
    hints_directory: /var/lib/cassandra/hints
    saved_caches_directory: /var/lib/cassandra/saved_caches
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: finstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:5.0.4
        ports:
        - containerPort: 9042
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: fintech
        - name: JVM_OPTS
          value: "-Xms256m -Xmx512m -XX:+UseG1GC"
        - name: CASSANDRA_CONFIG
          value: "/cassandra-config/cassandra.yaml"
        - name: CASSANDRA_DATA_DIR
          value: "/var/lib/cassandra/data"
        volumeMounts:
        - name: cassandra-data
          mountPath: "/var/lib/cassandra"
        - name: cassandra-config
          mountPath: "/cassandra-config/cassandra.yaml"
          subPath: cassandra.yaml
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "3Gi"
        securityContext:
          capabilities:
            add: ["IPC_LOCK", "SYS_RESOURCE"]
        livenessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9042
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-data-pvc
      - name: cassandra-config
        configMap:
          name: cassandra-config
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: finstream
spec:
  selector:
    app: cassandra
  ports:
  - port: 9042
    targetPort: 9042
  type: ClusterIP